apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ukb5p0j6b-go
  janus-idp.io/tekton: ukb5p0j6b-go
  backstage.io/kubernetes-id: ukb5p0j6b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ukb5p0j6b-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
