apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: ukb5p0j6b-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ukb5p0j6b-go 
  name: ukb5p0j6b-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ukb5p0j6b-go
    weight: 100 
