apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ukb5p0j6b-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ukb5p0j6b-go 
  name: ukb5p0j6b-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ukb5p0j6b-go 
